name: Ejercicio 4
on:
  workflow_dispatch:
jobs:
  generate-txt:
    runs-on: ubuntu-latest
    steps:
    - name: Crear archivo con mensaje
      run: echo "Hola, este mensaje fue creado en el Job 1" > mensaje.txt

    - name: Subir el archivo como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: mi-archivo-compartido
        path: mensaje.txt

  read-txt:
    runs-on: ubuntu-latest
    needs: generate-txt
    steps:
    - name: Descargar el artefacto
      uses: actions/download-artifact@v4
      with:
        name: mi-archivo-compartido

    - name: Mostrar contenido del archivo
      run: cat mensaje.txt