name: Welcome to the party (second)
on:
  workflow_dispatch:
jobs:
  say_hello:
    name: "Say Hello" 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"
      - uses: actions/checkout@v3
      - run: cat ./github/workflows/list.txt
        name: display list.txt
      - run: echo "I am the step 4"